// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1gTYvsvn5AcWa-pkgZEwpatDiMmcEQFk',
    appId: '1:706664211856:web:5be1c347d41de7bc903f15',
    messagingSenderId: '706664211856',
    projectId: 'bookreview-8f1b1',
    authDomain: 'bookreview-8f1b1.firebaseapp.com',
    storageBucket: 'bookreview-8f1b1.firebasestorage.app',
    measurementId: 'G-8NG9P2D7CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFPnSQU04ZJ69muDW1DzpSzwrLQjUNaE',
    appId: '1:706664211856:android:85dfdd756a468f42903f15',
    messagingSenderId: '706664211856',
    projectId: 'bookreview-8f1b1',
    storageBucket: 'bookreview-8f1b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHaOYFc6ChLIEp9CQp7bTli31_AKhuZqA',
    appId: '1:706664211856:ios:9373be2634e022d7903f15',
    messagingSenderId: '706664211856',
    projectId: 'bookreview-8f1b1',
    storageBucket: 'bookreview-8f1b1.firebasestorage.app',
    iosBundleId: 'com.example.bookreview',
  );
}
